In [1]:
#importing important libraries
import numpy as np
import pandas as pd
pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', None)

In [2]:
#loading dataset
df = pd.read_csv('/Users/HP/Downloads/student_marks_dataset/StudentsPerformance.csv')
print(df.head())

   gender race/ethnicity parental level of education test preparation course  math score  reading score  writing score
0  female        group B           bachelor's degree                    none          72             72             74
1  female        group C                some college               completed          69             90             88
2  female        group B             master's degree                    none          90             95             93
3    male        group A          associate's degree                    none          47             57             44
4    male        group C                some college                    none          76             78             75

In [3]:
#checking for missing values
print('missing values in each columns')
df.isnull().sum()

missing values in each columns

gender                         0
race/ethnicity                 1
parental level of education    0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [4]:
#checking duplicates
print('Duplicates columns')
df.duplicated()

Duplicates columns

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [5]:
#cleaning data by filling null values
df['race/ethnicity'].fillna('Unknown')

0      group B
1      group C
2      group B
3      group A
4      group C
        ...
995    group E
996    group C
997    group C
998    group D
999    group D
Name: race/ethnicity, Length: 1000, dtype: object

In [6]:
#again checking for null values
df.isnull().sum()

gender                         0
race/ethnicity                 1
parental level of education    0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#calculating total sore and average score
df['total score'] = df['math score']+ df['reading score']+ df['writing score']
df['average score'] = df['total score']/3
df.head()

   gender race/ethnicity parental level of education test preparation course  math score  reading score  writing score  total score  average score
0  female        group B           bachelor's degree                    none          72             72             74          218      72.666667
1  female        group C                some college               completed          69             90             88          247      82.333333
2  female        group B             master's degree                    none          90             95             93          278      92.666667
3    male        group A          associate's degree                    none          47             57             44          148      49.333333
4    male        group C                some college                    none          76             78             75          229      76.333333

In [10]:
#calculating minimum and maximum score
subjects = ['math score', 'reading score', 'writing score']
df['max score'] = df[subjects].max(axis=1)
df['min score'] = df[subjects].min(axis=1)
df.head()

   gender race/ethnicity parental level of education test preparation course  math score  reading score  writing score  total score  average score  max score  min score
0  female        group B           bachelor's degree                    none          72             72             74          218      72.666667         74         72
1  female        group C                some college               completed          69             90             88          247      82.333333         90         69
2  female        group B             master's degree                    none          90             95             93          278      92.666667         95         90
3    male        group A          associate's degree                    none          47             57             44          148      49.333333         57         44
4    male        group C                some college                    none          76             78             75          229      76.333333         78         75